# -*- coding: utf-8 -*-
"""Priya_Sah_GenAI_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NNf1ttpSey4LyjeV6s5KjYaqScXBftmZ
"""

# Install required libraries
!pip install transformers

# Import required modules
from transformers import pipeline, set_seed

# Load GPT-2 model and set seed
chatbot = pipeline('text-generation', model='gpt2')
set_seed(42)

# Define chatbot response function
def chatbot_response(prompt, max_length=100):
    responses = chatbot(prompt, max_length=max_length, num_return_sequences=1)
    return responses[0]['generated_text']

# Start a simple chat loop
while True:
    user_input = input("You: ")
    if user_input.lower() in ['exit', 'quit']:
        print("Chatbot: Goodbye!")
        break
    print("Chatbot:", chatbot_response(user_input))
